link_board_solution/config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  resources :posts, only: [:new, :create, :show] do
    resources :comments, only: [:index, :new, :create]
  end

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

end

link_board_solution/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

link_board_solution/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comment

  validates :title,
  presence: true,
  length: {
    minimum: 10,
    maximum: 100,
    too_short: "must be at least %{count} letters",
    too_long: "must be less than %{count} letters"
  }

  validates :link,
  presence: true,
  url: true
end

link_board_solution/app/models/user.rb
class User < ActiveRecord::Base
  has_many :post

  validates :email,
  presence: true,
  email: true,
  uniqueness: {case_sensitive: false}

  validates :name,
  presence: true,
  length: {
    maximum: 20,
    too_long: "must be less than %{count} letters"
  }

  validates :password,
  presence: true,
  length: {
    minimum: 8,
    maximum: 99,
    too_short: "must be greater than %{count} characters",
    too_long: "must be less than %{count} characters"
  },
  confirmation: true,
  on: :create

  has_secure_password

  def self.authenticate email, password
    User.find_by_email(email).try(:authenticate, password)
  end
end

link_board_solution/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def is_authenticated?
    unless current_user
      flash[:warning] = 'You need to login to do that'
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
end

link_board_solution/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :is_authenticated?, except: [:index]

  def index
    @post = Post.find params[:post_id]
  end

  def new
    @post = Post.find params[:post_id]
    @comment = Comment.new
  end

  def create
    Comment.create comment_params do |c|
      c.post_id = params[:post_id]
      c.user_id = @current_user.id
      c.save
    end
    redirect_to post_comments_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

link_board_solution/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_authenticated?, except: [:index]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create post_params do |p|
      p.user_id = @current_user.id
      p.save
    end
    if post.valid?
      flash[:success] = 'Post created'
      redirect_to root_path
    else
      messages = post.errors.map { |k, v| "#{k} #{v}" }
      flash[:danger] = messages.join(', ')
      redirect_to new_post_path
    end
  end

  def show
    @post = Post.find params[:id]
  end

  private

  def post_params
    params.require(:post).permit(:title, :link)
  end
end

link_board_solution/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate params[:user][:email], params[:user][:password]

    if user
      session[:user_id] = user.id
      flash[:success] = 'You are now logged in'
      redirect_to root_path
    else
      flash[:danger] = 'Username and/or password incorrect'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have been logged out'
    redirect_to root_path
  end
end

link_board_solution/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.create user_params
    if user.valid?
      session[:user_id] = user.id
      flash[:success] = 'User created and logged in'
      redirect_to root_path
    else
      messages = user.errors.map { |k, v| "#{k} #{v}" }
      flash[:danger] = messages.join(', ')
      redirect_to signup_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

link_board_solution/app/helpers/application_helper.rb
module ApplicationHelper
end

link_board_solution/app/helpers/comments_helper.rb
module CommentsHelper
end

link_board_solution/app/helpers/posts_helper.rb
module PostsHelper
end

link_board_solution/app/helpers/sessions_helper.rb
module SessionsHelper
end

link_board_solution/app/helpers/users_helper.rb
module UsersHelper
end

link_board_solution/app/views/comments/index.html.erb
<h1><%= link_to @post.title, @post.link %></h1>

<%= link_to 'New Comment', new_post_comment_path(@post), class: 'btn btn-primary' %>

<% @post.comment.each do |comment| %>
<div class="well">
  <p><%= comment.content %></p>
  <strong>By <%= comment.user.name %></strong>
</div>
<% end %>

link_board_solution/app/views/comments/new.html.erb
<h1>Post a Comment</h1>

<%= bootstrap_form_for [@post, @comment] do |f| %>
  <%= f.text_area :content %>

  <%= f.primary %>
<% end %>

link_board_solution/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <title>LinkBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'GA News', root_path, class: 'navbar-brand' %>
    </div>
  
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
      <% if @current_user %>
        <li><%= link_to 'Logout', logout_path %></li>
      <% else %>
        <li><%= link_to 'Signup', signup_path %></li>
        <li><%= link_to 'Login', login_path %></li>
      <% end %>
      </ul>
    <% if @current_user %>
      <p class="navbar-text navbar-right">Signed in as <%= @current_user.name %></p>
    <% end %>
    </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <%= render 'partials/alert' %>
  </div>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

link_board_solution/app/views/partials/_alert.html.erb
<% flash.each do |type, msg| %>
<div class="alert alert-<%= type %>"><%= msg %></div>
<% end %>

link_board_solution/app/views/posts/index.html.erb
<div class="row">
  <div class="col-xs-8">
    <h1>GA News</h1>
  </div>
  <div class="col-xs-4">
    <%= link_to '', new_post_path, class: 'btn btn-primary glyphicon glyphicon-plus pull-right' %>
  </div>
</div>

<% @posts.each do |post| %>
<div class="well">
  <h2><%= link_to post.title, post.link %></h2>
  <strong>By <%= post.user.name %></strong>
  <p><%= link_to 'Comments', post_comments_path(post) %></p>
</div>
<% end %>

link_board_solution/app/views/posts/new.html.erb
<h1>Create a new Post</h1>

<%= bootstrap_form_for @post, url: posts_path do |f| %>
  <%= f.text_field :title %>
  <%= f.url_field :link %>

  <%= f.primary %>
<% end %>

link_board_solution/app/views/users/new.html.erb
<h1>Signup</h1>

<%= bootstrap_form_for :user do |f| %>
  <%= f.email_field :email %>
  <%= f.text_field :name %>
  <%= f.password_field :password %>
  <%= f.password_field :password_confirmation %>

  <%= f.primary 'Signup' %>
<% end %>